import React, { useState } from 'react';
import {
  LineChart, Line, BarChart, Bar, PieChart, Pie, AreaChart, Area,
  XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Legend
} from 'recharts';
import {
  FileBarChart, CheckCircle2, ChevronRight, TrendingUp, TrendingDown,
  AlertCircle, Building2, Package, Wrench, Users, DollarSign
} from 'lucide-react';

import { DrillDownValue } from './DrillDownValue';

/* --- MOCK DATA FOR CHARTS --- */
const REVENUE_PACING = [
  { day: '1st', pacing: 45000, target: 50000 },
  { day: '5th', pacing: 210000, target: 250000 },
  { day: '10th', pacing: 520000, target: 500000 },
  { day: '15th', pacing: 890000, target: 750000 },
  { day: '20th', pacing: 1100000, target: 1000000 },
  { day: '25th', pacing: 1450000, target: 1250000 },
];

const AGING_BUCKETS = [
  { name: '0-30 Days', units: 42, value: 450000, floorplanInterest: 1200 },
  { name: '31-60 Days', units: 28, value: 310000, floorplanInterest: 3400 },
  { name: '61-90 Days', units: 18, value: 185000, floorplanInterest: 5800 },
  { name: '90+ Days', units: 14, value: 145000, floorplanInterest: 9500 },
];

const FI_MANAGERS = [
  { name: 'John D.', warranty: 45, prepaidMaint: 12, gap: 55, tireWheel: 22 },
  { name: 'Sarah M.', warranty: 52, prepaidMaint: 18, gap: 60, tireWheel: 30 },
  { name: 'Mike T.', warranty: 38, prepaidMaint: 8, gap: 42, tireWheel: 15 },
];

const TECH_EFFICIENCY = [
  { name: 'A. Smith', clocked: 40, billed: 31, eff: 78 },
  { name: 'B. Johnson', clocked: 45, billed: 52, eff: 115 },
  { name: 'C. Davis', clocked: 38, billed: 36, eff: 95 },
  { name: 'D. Wilson', clocked: 42, billed: 40, eff: 95 },
];

const LEAD_FUNNEL = [
  { stage: 'Raw Leads', count: 450 },
  { stage: 'Attempted Contact', count: 320 },
  { stage: 'Contacted', count: 180 },
  { stage: 'Appointments Set', count: 85 },
  { stage: 'Appointments Kept', count: 42 },
  { stage: 'Sold', count: 18 },
];

export const ReportsModule = ({ onDrillDown }) => {
  const [activeReportTab, setActiveReportTab] = useState('Executive Summary');

  const TABS = [
    { id: 'Executive Summary', label: 'Month-End Executive Summary' },
    { id: 'Aged Inventory', label: 'Aged Inventory Liability (90+)' },
    { id: 'FI Penetration', label: 'F&I Penetration by Product' },
    { id: 'Service Tech', label: 'Service Tech Efficiency YTD' },
    { id: 'Lost Leads', label: 'Lost Marketing Leads' }
  ];

  const renderContent = () => {
    switch(activeReportTab) {
      case 'Executive Summary':
        return (
          <>
            <div className="flex justify-between items-center mb-6">
              <div>
                 <h2 className="text-xl font-playfair text-white">Month-End Executive Summary</h2>
                 <div className="text-sm text-text-muted">Generated by Dealership OS AI Copilot • 2 mins ago</div>
              </div>
              <button className="text-gold text-sm border border-gold px-3 py-1 rounded hover:bg-gold hover:text-black transition-colors shadow shadow-gold/10" onClick={() => onDrillDown('Action', { name: 'Export PDF', message: 'Generating high-res PDF summary...' })}>Export PDF</button>
            </div>
            
            <div className="p-5 bg-black border border-border rounded-lg mb-6 text-sm text-text leading-relaxed shadow-inner">
              <span className="font-bold text-white block mb-2 font-mono uppercase tracking-wider text-xs flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-green-500" /> AI Synthesis:</span>
              Overall gross profitability is up <span className="text-green-500 font-bold bg-green-900/20 px-1 rounded">14.2%</span> compared to the same period last year, driven entirely by F&I back-end products attached to used non-current inventory. However, service department labor gross has dropped <span className="text-amber-500 font-bold bg-amber-900/20 px-1 rounded">6%</span> due to an increase in unbilled warranty diagnosis time at the Slidell location. Immediate attention to service writing processes is recommended.
            </div>

            <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                <div className="bg-charcoal border border-border p-5 rounded-lg text-center cursor-pointer hover:border-gold transition-colors shadow-inner" onClick={() => onDrillDown('Report', {metric: 'Front-End Gross'})}>
                   <div className="text-xs text-text-dim uppercase tracking-wider mb-2 font-mono flex items-center justify-center gap-2"><Building2 className="w-4 h-4 text-text-muted" /> Front-End Gross</div>
                   <div className="text-3xl font-playfair font-bold text-white">
                      <DrillDownValue value="$412,850" label="Front-End Gross" type="Report" onDrillDown={onDrillDown} />
                   </div>
                   <div className="text-xs text-green-500 mt-2 font-bold tracking-wider">+4.2% YoY</div>
                </div>
                <div className="bg-charcoal border border-border p-5 rounded-lg text-center cursor-pointer hover:border-gold transition-colors shadow-inner" onClick={() => onDrillDown('Report', {metric: 'Back-End Gross'})}>
                   <div className="text-xs text-text-dim uppercase tracking-wider mb-2 font-mono flex items-center justify-center gap-2"><DollarSign className="w-4 h-4 text-text-muted" /> Back-End Gross</div>
                   <div className="text-3xl font-playfair font-bold text-green-400">
                      <DrillDownValue value="$218,440" label="Back-End Gross" type="Report" onDrillDown={onDrillDown} color="text-green-400" />
                   </div>
                   <div className="text-xs text-green-500 mt-2 font-bold tracking-wider">+18.5% YoY</div>
                </div>
                <div className="bg-charcoal border border-border p-5 rounded-lg text-center cursor-pointer hover:border-gold transition-colors shadow-inner" onClick={() => onDrillDown('Report', {metric: 'Fixed Operations'})}>
                   <div className="text-xs text-text-dim uppercase tracking-wider mb-2 font-mono flex items-center justify-center gap-2"><Wrench className="w-4 h-4 text-text-muted" /> Fixed Ops Gross</div>
                   <div className="text-3xl font-playfair font-bold text-amber-500">
                      <DrillDownValue value="$188,200" label="Fixed Ops Gross" type="Report" onDrillDown={onDrillDown} color="text-amber-500" />
                   </div>
                   <div className="text-xs text-red-500 mt-2 font-bold tracking-wider">-6.0% YoY</div>
                </div>
                <div className="bg-charcoal border border-gold/30 p-5 rounded-lg text-center cursor-pointer hover:border-gold transition-colors shadow-[0_0_15px_rgba(201,168,76,0.1)] relative overflow-hidden" onClick={() => onDrillDown('Report', {metric: 'Total Net Dealership'})}>
                   <div className="absolute top-0 right-0 w-16 h-16 bg-gold/10 rounded-full blur-xl translate-x-4 -translate-y-4"></div>
                   <div className="text-xs text-gold uppercase tracking-wider mb-2 font-mono flex items-center justify-center gap-2 relative z-10"><TrendingUp className="w-4 h-4" /> Dealership Net</div>
                   <div className="text-3xl font-playfair font-bold text-gold relative z-10">$124,105</div>
                   <div className="text-xs text-green-500 mt-2 font-bold tracking-wider relative z-10">+14.2% YoY</div>
                </div>
            </div>

            <div className="bg-black border border-border rounded-lg p-6 flex flex-col shadow-inner">
               <h3 className="text-sm font-bold text-white mb-4 uppercase tracking-widest font-mono border-b border-border/50 pb-2 flex justify-between">
                 <span>Revenue Pacing vs Forecast</span>
                 <span className="text-text-muted">MTD Run Rate</span>
               </h3>
               <div className="h-64 mt-2">
                 <ResponsiveContainer width="100%" height="100%">
                   <AreaChart data={REVENUE_PACING} margin={{top:10, right:10, left:20, bottom:0}}>
                     <defs>
                        <linearGradient id="colorPacing" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="5%" stopColor="#c9a84c" stopOpacity={0.3}/>
                          <stop offset="95%" stopColor="#c9a84c" stopOpacity={0}/>
                        </linearGradient>
                     </defs>
                     <CartesianGrid strokeDasharray="3 3" stroke="#333" vertical={false} />
                     <XAxis dataKey="day" stroke="#888" tick={{fill: '#888', fontSize: 12}} axisLine={false} tickLine={false} />
                     <YAxis stroke="#888" tick={{fill: '#888', fontSize: 12}} tickFormatter={(v) => `$${v/1000}k`} axisLine={false} tickLine={false} />
                     <Tooltip 
                        contentStyle={{backgroundColor: '#111', borderColor: '#333', borderRadius: '8px'}}
                        itemStyle={{color: '#fff'}}
                        formatter={(value) => `$${value.toLocaleString()}`}
                     />
                     <Legend wrapperStyle={{fontSize: '12px'}} />
                     <Area type="monotone" dataKey="pacing" name="Actual Pacing" stroke="#c9a84c" strokeWidth={3} fillOpacity={1} fill="url(#colorPacing)" />
                     <Line type="stepAfter" dataKey="target" name="Forecast Target" stroke="#888" strokeWidth={2} strokeDasharray="5 5" dot={false} />
                   </AreaChart>
                 </ResponsiveContainer>
               </div>
            </div>
          </>
        );

      case 'Aged Inventory':
        return (
          <>
            <div className="flex justify-between items-center mb-6">
              <div>
                 <h2 className="text-xl font-playfair text-white">Aged Inventory Liability (90+)</h2>
                 <div className="text-sm text-text-muted">Generated by Dealership OS AI Copilot • 14 mins ago</div>
              </div>
              <button className="text-gold text-sm border border-gold px-3 py-1 rounded hover:bg-gold hover:text-black transition-colors" onClick={() => onDrillDown('Action', { name: 'Batch Export', message: 'Generating CSV...' })}>Export CSV</button>
            </div>
            
            <div className="p-5 bg-black border border-red-900/30 rounded-lg mb-6 text-sm text-text leading-relaxed shadow-inner">
              <span className="font-bold text-white block mb-2 font-mono uppercase tracking-wider text-xs flex items-center gap-2"><AlertCircle className="w-4 h-4 text-red-500 animate-pulse" /> AI Risk Synthesis:</span>
              <span className="text-red-400 font-bold">14 units</span> have crossed the critical 90-day threshold, representing <span className="text-white font-bold bg-panel px-1">$145,000</span> in tied-up capital. Accrued floorplan interest is projecting to severely impact departmental net next month. AI recommends triggering the automated Markdown Protocol (-10%) on the 5 oldest units immediately to stimulate turn.
            </div>

            <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                <div className="bg-charcoal border border-border p-5 rounded-lg text-center cursor-pointer hover:border-gold transition-colors shadow-inner" onClick={() => onDrillDown('Report', {metric: 'Active Inventory Value'})}>
                   <div className="text-xs text-text-dim uppercase tracking-wider mb-2 font-mono">Total Capital Risk</div>
                   <div className="text-3xl font-playfair font-bold text-white">
                      <DrillDownValue value="$1,090,000" label="Total Capital Value" type="Report" onDrillDown={onDrillDown} />
                   </div>
                </div>
                <div className="bg-charcoal border border-border p-5 rounded-lg text-center cursor-pointer hover:border-gold transition-colors shadow-inner" onClick={() => onDrillDown('Report', {metric: '90 Day Units'})}>
                   <div className="text-xs text-text-dim uppercase tracking-wider mb-2 font-mono">90+ Day Units</div>
                   <div className="text-3xl font-playfair font-bold text-red-500">
                      <DrillDownValue value="14" label="90+ Day Units" type="Report" onDrillDown={onDrillDown} color="text-red-500" />
                   </div>
                </div>
                <div className="bg-charcoal border border-border p-5 rounded-lg text-center cursor-pointer hover:border-gold transition-colors shadow-inner" onClick={() => onDrillDown('Report', {metric: 'Floorplan Expense'})}>
                   <div className="text-xs text-text-dim uppercase tracking-wider mb-2 font-mono">YTD Interest Carry</div>
                   <div className="text-3xl font-playfair font-bold text-amber-500">
                      <DrillDownValue value="$19,900" label="Floorplan Expense" type="Report" onDrillDown={onDrillDown} color="text-amber-500" />
                   </div>
                </div>
                <div className="bg-panel border border-border p-5 rounded-lg flex items-center justify-center hover:bg-black transition-colors shadow-inner">
                   <button className="w-full h-full flex flex-col items-center justify-center text-red-400 font-bold tracking-widest uppercase text-sm border border-red-900/50 bg-red-900/10 hover:bg-red-900/30 rounded py-2 transition-colors" onClick={() => onDrillDown('Action', {name: 'Trigger 10% Markdown on 90+ aged units'})}>
                     <TrendingDown className="w-6 h-6 mb-1" />
                     Trigger Markdown
                   </button>
                </div>
            </div>

            <div className="bg-black border border-border rounded-lg p-6 flex flex-col shadow-inner">
               <h3 className="text-sm font-bold text-white mb-4 uppercase tracking-widest font-mono border-b border-border/50 pb-2">Aging Buckets Distribution</h3>
               <div className="h-64 mt-2">
                 <ResponsiveContainer width="100%" height="100%">
                   <BarChart data={AGING_BUCKETS} margin={{top:10, right:10, left:0, bottom:0}}>
                     <CartesianGrid strokeDasharray="3 3" stroke="#333" vertical={false} />
                     <XAxis dataKey="name" stroke="#888" tick={{fill: '#888', fontSize: 12}} axisLine={false} tickLine={false} />
                     <YAxis yAxisId="left" orientation="left" stroke="#888" tick={{fill: '#888', fontSize: 12}} axisLine={false} tickLine={false} />
                     <YAxis yAxisId="right" orientation="right" stroke="#c9a84c" tick={{fill: '#c9a84c', fontSize: 12}} tickFormatter={(v) => `$${v}`} axisLine={false} tickLine={false} />
                     <Tooltip contentStyle={{backgroundColor: '#111', borderColor: '#333', borderRadius: '8px'}} itemStyle={{color: '#fff'}} cursor={{fill: '#222'}} />
                     <Legend wrapperStyle={{fontSize: '12px'}} />
                     <Bar yAxisId="left" dataKey="units" name="Total Units" fill="#3b82f6" radius={[4,4,0,0]} barSize={40} />
                     <Bar yAxisId="right" dataKey="floorplanInterest" name="Floorplan Accrual ($)" fill="#ef4444" radius={[4,4,0,0]} barSize={40} />
                   </BarChart>
                 </ResponsiveContainer>
               </div>
            </div>
          </>
        );

      case 'FI Penetration':
        return (
          <>
            <div className="flex justify-between items-center mb-6">
              <div>
                 <h2 className="text-xl font-playfair text-white">F&I Penetration by Product</h2>
                 <div className="text-sm text-text-muted">Generated by Dealership OS AI Copilot • 1 hr ago</div>
              </div>
              <button className="text-gold text-sm border border-gold px-3 py-1 rounded hover:bg-gold hover:text-black transition-colors" onClick={() => onDrillDown('Action', { name: 'Print Comm Matrix' })}>Print Roster</button>
            </div>
            
            <div className="p-5 bg-black border border-border rounded-lg mb-6 text-sm text-text leading-relaxed shadow-inner">
              <span className="font-bold text-white block mb-2 font-mono uppercase tracking-wider text-xs flex items-center gap-2"><TrendingUp className="w-4 h-4 text-green-500" /> AI Synthesis:</span>
              Extended Service Contract (ESC) penetration is excelling at <span className="text-green-500 font-bold">45%</span>, but Prepaid Maintenance has dropped to <span className="text-red-500 font-bold">12%</span>. Sarah M. is leading the board in ESC attach rate (52%), neutralizing the loss in maintenance gross. AI recommends retargeting recent cash buyers via CRM logic to boost Prepaid Maintenance post-sale.
            </div>

            <div className="bg-black border border-border rounded-lg p-6 flex flex-col shadow-inner">
               <h3 className="text-sm font-bold text-white mb-4 uppercase tracking-widest font-mono border-b border-border/50 pb-2">Manager Performance Stack (%)</h3>
               <div className="h-72 mt-2">
                 <ResponsiveContainer width="100%" height="100%">
                   <BarChart data={FI_MANAGERS} layout="vertical" margin={{top:0, right:30, left:20, bottom:0}}>
                     <CartesianGrid strokeDasharray="3 3" stroke="#333" horizontal={false} />
                     <XAxis type="number" domain={[0, 100]} stroke="#888" tick={{fill: '#888', fontSize: 12}} axisLine={false} tickLine={false} />
                     <YAxis type="category" dataKey="name" stroke="#888" tick={{fill: '#white', fontSize: 14, fontWeight: 'bold'}} axisLine={false} tickLine={false} />
                     <Tooltip contentStyle={{backgroundColor: '#111', borderColor: '#333', borderRadius: '8px'}} itemStyle={{color: '#fff'}} cursor={{fill: '#222'}} />
                     <Legend wrapperStyle={{fontSize: '12px'}} />
                     <Bar dataKey="warranty" name="ESC Warranty" stackId="a" fill="#c9a84c" barSize={30} />
                     <Bar dataKey="gap" name="GAP" stackId="a" fill="#3b82f6" />
                     <Bar dataKey="tireWheel" name="Tire & Wheel" stackId="a" fill="#10b981" />
                     <Bar dataKey="prepaidMaint" name="Prepaid Maint" stackId="a" fill="#ef4444" radius={[0,4,4,0]} />
                   </BarChart>
                 </ResponsiveContainer>
               </div>
            </div>
          </>
        );

      case 'Service Tech':
        return (
          <>
            <div className="flex justify-between items-center mb-6">
              <div>
                 <h2 className="text-xl font-playfair text-white">Service Tech Efficiency YTD</h2>
                 <div className="text-sm text-text-muted">Generated by Dealership OS AI Copilot • 4 hrs ago</div>
              </div>
              <button className="text-gold text-sm border border-gold px-3 py-1 rounded hover:bg-gold hover:text-black transition-colors" onClick={() => onDrillDown('Action', { name: 'Payroll Sync' })}>Sync Payroll</button>
            </div>
            
            <div className="p-5 bg-black border border-border rounded-lg mb-6 text-sm text-text leading-relaxed shadow-inner">
              <span className="font-bold text-white block mb-2 font-mono uppercase tracking-wider text-xs flex items-center gap-2"><Wrench className="w-4 h-4 text-amber-500" /> AI Synthesis:</span>
              Overall shop efficiency is stable at <span className="text-green-500 font-bold">92%</span>. However, Master Tech 'A. Smith' has dropped to <span className="text-red-500 font-bold">78%</span> due to parts delays on warranty claims. AI recommends shifting quick-lube overflow to his bay to maintain throughput and unapplied time.
            </div>

            <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
                <div className="bg-charcoal border border-border p-5 rounded-lg text-center cursor-pointer hover:border-gold transition-colors shadow-inner" onClick={() => onDrillDown('Report', {metric: 'Billed Hours'})}>
                   <div className="text-xs text-text-dim uppercase tracking-wider mb-2 font-mono">Billed Flat Rate</div>
                   <div className="text-3xl font-playfair font-bold text-white">
                      <DrillDownValue value="159.0" label="Billed Flat Rate" type="Report" onDrillDown={onDrillDown} />
                   </div>
                </div>
                <div className="bg-charcoal border border-border p-5 rounded-lg text-center cursor-pointer hover:border-gold transition-colors shadow-inner" onClick={() => onDrillDown('Report', {metric: 'Clocked Hours'})}>
                   <div className="text-xs text-text-dim uppercase tracking-wider mb-2 font-mono">Clocked Time</div>
                   <div className="text-3xl font-playfair font-bold text-amber-300">
                      <DrillDownValue value="165.0" label="Clocked Hours" type="Report" onDrillDown={onDrillDown} color="text-amber-300" />
                   </div>
                </div>
                <div className="bg-charcoal border border-border p-5 rounded-lg text-center cursor-pointer hover:border-gold transition-colors shadow-inner" onClick={() => onDrillDown('Report', {metric: 'Shop Efficiency'})}>
                   <div className="text-xs text-text-dim uppercase tracking-wider mb-2 font-mono">Total Shop Eff.</div>
                   <div className="text-3xl font-playfair font-bold text-green-500">
                      <DrillDownValue value="92.1%" label="Shop Efficiency" type="Report" onDrillDown={onDrillDown} color="text-green-500" />
                   </div>
                </div>
                <div className="bg-charcoal border border-red-500/30 p-5 rounded-lg flex items-center justify-center hover:bg-black transition-colors shadow-inner cursor-pointer" onClick={() => onDrillDown('Report', {metric: 'Unapplied Time Analytics'})}>
                   <div className="text-center">
                     <div className="text-xs text-red-500 uppercase tracking-wider mb-2 font-mono font-bold">UNAPPLIED FLAG</div>
                     <div className="text-2xl font-bold font-mono text-white">6.0 HRS</div>
                   </div>
                </div>
            </div>

            <div className="bg-black border border-border rounded-lg p-6 flex flex-col shadow-inner">
               <h3 className="text-sm font-bold text-white mb-4 uppercase tracking-widest font-mono border-b border-border/50 pb-2">Clocked vs Billed by Tech</h3>
               <div className="h-64 mt-2">
                 <ResponsiveContainer width="100%" height="100%">
                   <BarChart data={TECH_EFFICIENCY} margin={{top:10, right:10, left:0, bottom:0}}>
                     <CartesianGrid strokeDasharray="3 3" stroke="#333" vertical={false} />
                     <XAxis dataKey="name" stroke="#888" tick={{fill: '#888', fontSize: 12}} axisLine={false} tickLine={false} />
                     <YAxis stroke="#888" tick={{fill: '#888', fontSize: 12}} axisLine={false} tickLine={false} />
                     <Tooltip contentStyle={{backgroundColor: '#111', borderColor: '#333', borderRadius: '8px'}} itemStyle={{color: '#fff'}} cursor={{fill: '#222'}} />
                     <Legend wrapperStyle={{fontSize: '12px'}} />
                     <Bar dataKey="clocked" name="Clocked (Actual) Hrs" fill="#888" radius={[4,4,0,0]} barSize={20} />
                     <Bar dataKey="billed" name="Billed (Flat Rate) Hrs" fill="#10b981" radius={[4,4,0,0]} barSize={20} />
                   </BarChart>
                 </ResponsiveContainer>
               </div>
            </div>
          </>
        );

      case 'Lost Leads':
        return (
          <>
            <div className="flex justify-between items-center mb-6">
              <div>
                 <h2 className="text-xl font-playfair text-white">Lost Marketing Leads</h2>
                 <div className="text-sm text-text-muted">Generated by Dealership OS AI Copilot • 10 mins ago</div>
              </div>
              <button className="text-gold text-sm border border-gold px-3 py-1 rounded hover:bg-gold hover:text-black transition-colors" onClick={() => onDrillDown('Action', { name: 'Audit BDC Matrix' })}>Audit CRM Sync</button>
            </div>
            
            <div className="p-5 bg-black border border-border rounded-lg mb-6 text-sm text-text leading-relaxed shadow-inner">
              <span className="font-bold text-white block mb-2 font-mono uppercase tracking-wider text-xs flex items-center gap-2"><Users className="w-4 h-4 text-blue-500" /> AI Synthesis:</span>
              <span className="text-red-500 font-bold">32%</span> of all inbound digital leads are dying between the "Raw" and "Attempted Contact" stages. Response time is aggressively healthy (14m avg), suggesting lead quality from Facebook Lead Ads is degraded or BDC scripting strategy requires immediate permutation.
            </div>

            <div className="bg-black border border-border rounded-lg p-6 flex flex-col shadow-inner">
               <h3 className="text-sm font-bold text-white mb-4 uppercase tracking-widest font-mono border-b border-border/50 pb-2">Funnel Attrition Visualization</h3>
               <div className="h-72 mt-2">
                 <ResponsiveContainer width="100%" height="100%">
                   <AreaChart data={LEAD_FUNNEL} margin={{top:10, right:30, left:0, bottom:0}}>
                     <defs>
                        <linearGradient id="colorLeads" x1="0" y1="0" x2="0" y2="1">
                          <stop offset="5%" stopColor="#3b82f6" stopOpacity={0.5}/>
                          <stop offset="95%" stopColor="#3b82f6" stopOpacity={0}/>
                        </linearGradient>
                     </defs>
                     <CartesianGrid strokeDasharray="3 3" stroke="#333" vertical={false} />
                     <XAxis dataKey="stage" stroke="#888" tick={{fill: '#888', fontSize: 11}} axisLine={false} tickLine={false} />
                     <YAxis stroke="#888" tick={{fill: '#888', fontSize: 12}} axisLine={false} tickLine={false} />
                     <Tooltip 
                        contentStyle={{backgroundColor: '#111', borderColor: '#333', borderRadius: '8px'}}
                        itemStyle={{color: '#fff'}}
                     />
                     <Area type="monotone" dataKey="count" name="Live Leads" stroke="#3b82f6" strokeWidth={3} fillOpacity={1} fill="url(#colorLeads)" />
                   </AreaChart>
                 </ResponsiveContainer>
               </div>
            </div>
          </>
        );

      default:
        return <div className="text-center p-8 text-text-muted">Select a valid report.</div>;
    }
  };

  return (
    <div className="max-w-7xl mx-auto space-y-6">
       <div className="flex items-center justify-between border-b border-border pb-4 mb-6 sticky top-0 bg-black/80 backdrop-blur-md z-20">
         <h1 className="text-3xl font-playfair text-white flex items-center gap-3">
           <FileBarChart className="w-8 h-8 text-gold" /> Dealership Analytics Hub
         </h1>
         <div className="flex gap-2">
            <button className="bg-charcoal hover:bg-black text-white font-bold py-2 px-4 rounded border border-border transition-colors shadow-inner text-sm tracking-wide" onClick={() => onDrillDown('Action', { name: 'Schedule Report', message: 'Opening report scheduler...' })}>
               Schedule Report
            </button>
            <button className="bg-gold hover:bg-gold-light text-black font-bold py-2 px-4 rounded transition-colors shadow-lg shadow-gold/20 flex items-center gap-2 text-sm tracking-wide" onClick={() => onDrillDown('Action', { name: 'Create Custom Query', message: 'Opening advanced query builder...' })}>
               + Create Custom Query
            </button>
         </div>
       </div>

       <div className="flex flex-col md:flex-row gap-6">
          <div className="w-full md:w-64 space-y-2 shrink-0 border-r border-border pr-6">
             <div className="text-[10px] font-mono text-text-muted uppercase tracking-widest mb-4">Saved Matrix Views</div>
             {TABS.map(tab => {
                const isActive = activeReportTab === tab.id;
                return (
                  <button 
                    key={tab.id}
                    className={`w-full text-left p-3.5 rounded transition-all text-sm block ${isActive ? 'bg-panel border-l-2 border-gold text-white font-bold shadow-md' : 'hover:bg-charcoal text-text-muted hover:text-white border-l-2 border-transparent'}`}
                    onClick={() => setActiveReportTab(tab.id)}
                  >
                    {tab.label}
                  </button>
                )
             })}
          </div>
          
          <div className="flex-1 space-y-6 bg-charcoal border border-border rounded-xl p-8 relative overflow-hidden shadow-2xl">
             {/* Decorative Background Glow */}
             <div className="absolute top-0 right-0 w-96 h-96 bg-gold/5 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2 pointer-events-none"></div>
             
             <div className="relative z-10 animate-in fade-in zoom-in-95 duration-300" key={activeReportTab}>
               {renderContent()}
             </div>
          </div>
       </div>
       <div className="mt-8"></div>
     </div>
  );
};
